SKILLS = [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "HTML",
    "CSS",
    "SQL",
    "Git",
    "GitHub",
    "Machine Learning",
    "Data Analysis",
    "Flask",
    "Django",
    "React",
    "Node.js",
    "Docker",
    "Linux",
    "Communication",
    "Leadership",
    "Problem Solving",
    "Teamwork",
    "Time Management"
]
